// <auto-generated />
using System;
using BankAccountManagementSystem.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountManagementSystem.Migrations
{
    [DbContext(typeof(ContextClass))]
    [Migration("20230727102533_TableChanges")]
    partial class TableChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankAccountManagementSystem.Model.AccountType", b =>
                {
                    b.Property<Guid>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeOfAccount")
                        .HasColumnType("int");

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypesDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccountClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmountOfBalance")
                        .HasColumnType("int");

                    b.HasKey("BankAccountId");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("BankAccountsDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankAccountPostingDetails", b =>
                {
                    b.Property<Guid>("PostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostingDetailsTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostingId");

                    b.HasIndex("PostingDetailsTransactionId");

                    b.ToTable("BankAccountPostingDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasMaxLength(6)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CatagoryOptions")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstNameOfTransactionPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNameOfTransactionPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNameOfTransactionPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeOfTransaction")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("PaymentId");

                    b.ToTable("BankTransactionDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NameOfPaymentType")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankAccount", b =>
                {
                    b.HasOne("BankAccountManagementSystem.Model.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankAccountPostingDetails", b =>
                {
                    b.HasOne("BankAccountManagementSystem.Model.BankTransaction", "PostingDetails")
                        .WithMany()
                        .HasForeignKey("PostingDetailsTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostingDetails");
                });

            modelBuilder.Entity("BankAccountManagementSystem.Model.BankTransaction", b =>
                {
                    b.HasOne("BankAccountManagementSystem.Model.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankAccountManagementSystem.Model.Payment", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("PaymentMethod");
                });
#pragma warning restore 612, 618
        }
    }
}
